# Generated by Django 5.2 on 2025-05-10 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('noticeid', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal', models.CharField(max_length=45)),
                ('event', models.CharField(max_length=45)),
                ('judul', models.CharField(max_length=45)),
                ('description', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SlotParkir',
            fields=[
                ('slotparkirid', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=45, unique=True)),
                ('password', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=45, unique=True)),
                ('role', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='ParkiranTertutup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.notice')),
                ('slotparkir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.slotparkir')),
            ],
        ),
        migrations.CreateModel(
            name='Laporan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.BinaryField()),
                ('lokasi', models.CharField(blank=True, max_length=45, null=True)),
                ('status', models.CharField(max_length=45)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.user')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('status', models.CharField(max_length=45)),
                ('totalharga', models.IntegerField()),
                ('slotparkir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.slotparkir')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.user')),
            ],
        ),
    ]
