# Generated by Django 5.2 on 2025-06-07 11:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_remove_booking_userid_remove_laporan_userid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laporan',
            name='tanggal',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
