# Generated by Django 5.2 on 2025-06-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='laporan',
            name='topic',
            field=models.CharField(default='Parkir Sembarangan', max_length=45),
        ),
    ]
