# Generated by Django 5.2 on 2025-06-17 08:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_laporan_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='tanggal',
        ),
        migrations.AddField(
            model_name='notice',
            name='tanggalfrom',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notice',
            name='tanggaluntil',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
