# Generated by Django 5.2.1 on 2025-06-18 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_booking_created_at'),
        ('App', '0007_remove_notice_tanggal_notice_tanggalfrom_and_more'),
    ]

    operations = [
    ]
