# Generated by Django 5.2 on 2025-06-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_merge_20250618_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='tanggalfrom',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='tanggaluntil',
            field=models.DateField(blank=True, null=True),
        ),
    ]
